name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  npm-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: node_modules cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-npm-ci-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  unit-test:
    runs-on: ubuntu-latest
    needs: npm-ci
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Run prettier check
        run: npm run format:ci
      - name: Run lint check
        run: npm run lint
      - name: Run typecheck
        run: npm run typecheck
      - name: Run unit tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: npm-ci
    steps:
      - name: nextjs cache
        uses: actions/cache@v2
        with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Run build
        run: npm run build:ci

  cypress-test:
    runs-on: ubuntu-latest
    needs: [npm-ci, build]
    steps:
      - name: Run build
        run: npm run build:ci
      - name: Start server
        run: |
          PORT=3000 npm run start &
          sleep 5 && 
          curl http://localhost:3000/api/status -I
      - name: Cypress run
        uses: cypress-io/github-action@v2.7.0
        with:
          record: true
          quiet: true
          # we have already installed all dependencies above
          install: false
        env:
          DB_PATH: ./db/game.sqlite
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
